from pathlib import Path
import os,json,hashlib,importlib.util,fcntl,subprocess,datetime
R=Path('/tmp/n7-f10-atomic-admission-negatives-a33');A=Path('/tmp/n7-f10-atomic-admission-verify-a32');P=Path('/tmp/n7-f10-restart-fix-20261006-a12/projects/07-cold-email-warmup');sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat();write=lambda n,x:(R/n).write_text(json.dumps(x,indent=2)+'\n');ctx=json.loads((R/'launch-actual.json').read_text());spec=importlib.util.spec_from_file_location('nr',R/'native-run-a33.py');nr=importlib.util.module_from_spec(spec);spec.loader.exec_module(nr)
assert datetime.datetime.now(datetime.timezone.utc)<datetime.datetime.fromisoformat(ctx['deadline_utc']);assert not nr.nodes();lock=open('/tmp/codex-heavy-build.lock','rb');fcntl.flock(lock,fcntl.LOCK_EX|fcntl.LOCK_NB)
try:
 source=nr.candidate_check();pg=nr.snapshot();db=nr.status();assert pg['quiescent'];assert db['counts']=={'occupied_slots':0,'runtime_claims':0,'other_sessions':0};inv=json.loads((R/'input-inventory-a33.json').read_text());shadow=[f for f,h in inv['shadow_files'].items() if sha(R/'compact-shadow-a33'/f)!=h];assert not shadow
 legacy={str(p):sha(p) for p in [Path('/tmp/n7-f10-cadence-implement-a7/short-native-v2.json'),Path('/tmp/n7-f10-cadence-implement-a7/short-native-v2-drain.json')]};assert list(legacy.values())==['60d07dcb6bcec2d5faa0419f86ccb41fce2997564376df6f25d197f5b4ce1007','3d19f0b8d4ed427ae24293f9d897c17f0165ef5bc6132b2fffbd8af01f663b2a']
 prev=json.loads((A/'raw-artifact-manifest.json').read_text());assert sha(A/'raw-artifact-manifest.json')=='562007f57c9af0fc58e289fe892ddb239c1fd736c9ea7aa611bc7ad762dc76aa';prevdrift=[f for f,v in prev['files'].items() if sha(A/f)!=v['sha256']];assert not prevdrift
 write('terminal-ownership-a33.json',{'utc':now(),'source120_build73_sql15_drift':source,'shadow177_drift':shadow,'owned_nodes':nr.nodes(),'PG':pg,'DB':db,'legacy_original_hashes':legacy,'A32_raw_manifest_SHA':sha(A/'raw-artifact-manifest.json'),'A32_verified_file_count':len(prev['files']),'A32_artifact_drift':prevdrift,'protected_dependency_realpath':str((P/'node_modules').resolve()),'disk_available_bytes':os.statvfs('/').f_bavail*os.statvfs('/').f_frsize,'mutex':'exclusive acquired, released after this proof'})
finally:fcntl.flock(lock,fcntl.LOCK_UN);lock.close()
write('mandatory-remainder-a33.json',{'utc':now(),'source_head':ctx['source_head'],'product_acceptance':False,'next_executor':'coordinator to actually launch distinct bounded HIGH diagnostic follow-up; confirmed fixture changes require fresh MEDIUM author','required':[{'name':'atomic-cancel-unused-leak','state':'native timeout; not caught','raw':['atomic-cancel-unused-leak-negative-timeout.json','atomic-cancel-unused-leak-negative-exit.json','atomic-cancel-unused-leak-store.ts.patch','atomic-cancel-timeout-restored-exit.json'],'diagnosis':'PG sessions idle ClientRead, no blockers, stderr empty; no causal conclusion; actual owned timeout joins preserved; restored positive0 and test residue cleared only after joined/quiescent/source/mutex proof','next':'isolate cancel and existing real abort-after-COMMIT with named bounded physical-slot-count assertion before child start; exact source binding, baseline0/material assertion/restored0; no blind 70s replay'},{'name':'native-runtime-result-guard-drop','state':'unrun fixed budget','title':'settled native UID reset proof cannot bypass runtime poll source run grant or mailbox fences'},{'name':'native-transport-result-guard-drop','state':'unrun fixed budget','title':'settled native UID reset proof cannot bypass runtime poll source run grant or mailbox fences'},{'name':'abort-specific material seam','state':'existing real PG positive verified, material mutation not isolated','next':'use existing abort-after-COMMIT PG witness; no assertion of missing positive coverage'},{'name':'fresh independent source review','state':'separate new fork-none HIGH actor after mandatory operational gaps'}],'no_source_fix_authorized_by_timeout':True})
subprocess.run(['python3',str(R/'canary-a33.py')],check=True,env=os.environ)
canary=json.loads((R/'canary-result-a33.json').read_text());mat=json.loads((R/'material-results-a33.json').read_text());short=json.loads((R/'short-remainder-results.json').read_text());slots=json.loads((R/'slot-mutation-results.json').read_text());caught=[x for x in mat+short if x.get('status')=='caught_material_assertion'];assert len(caught)==22;assert len(slots)==5 and all(x['status']=='caught_material_assertion' for x in slots)
write('material-reconciliation-final-a33.json',{'utc':now(),'completed_combined_material_count':len(caught),'completed_slot_material_count':len(slots),'caught_names':[x['name'] for x in caught],'slot_names':[x['name'] for x in slots],'predicate':'native baseline0, mutated native nonzero ERR_ASSERTION and named failing test, actual restored0; timeouts/import/compiler failures excluded','actual_quota_negative_titles':['B1/B2 SC-US-003-4 limit'],'planned_B5_midnight_branch':'not exercised by quota negative; no inferred coverage','native_delay_binding':'source and compiled dist both mutated; negative actual44.319s, restored actual0','unresolved':'cancel native timeout plus two pending result-fence mutations; abort-specific mutation isolated in next phase'})
terminal=now();elapsed=(datetime.datetime.fromisoformat(terminal)-datetime.datetime.fromisoformat(ctx['actual_ack_utc'])).total_seconds();assert elapsed<1200
write('final-context-a33.json',{**ctx,'terminal_utc':terminal,'elapsed_seconds':elapsed,'verification_status':'PARTIAL_WITH_MANDATORY_REMAINDER','product_acceptance':False,'actual_model':None,'actual_effort':None,'usage':None,'cost':None})
write('terminal-receipt-a33.json',{'utc':terminal,'run_id':ctx['run_id'],'source_head':ctx['source_head'],'profile':'model-routing-econom','requested_model':'gpt-6.1-sol','requested_effort':'high','actual_model':None,'actual_effort':None,'usage':None,'cost':None,'elapsed_seconds':elapsed,'positive_F09_exact5_native_exit':0,'combined_material_caught':22,'combined_material_total':25,'slot_material_caught':5,'slot_material_total':5,'timeout_case':'atomic-cancel-unused-leak','timeout_counted_caught':False,'restored_timeout_fixture_actual_exit':0,'remaining':['cancellation witness diagnosis','runtime result fence mutation','transport result fence mutation','isolated abort-seam mutation','separate fresh HIGH source review'],'ownership_sha256':sha(R/'terminal-ownership-a33.json'),'material_reconciliation_sha256':sha(R/'material-reconciliation-final-a33.json'),'canary_sha256':sha(R/'canary-result-a33.json'),'canary':{k:canary[k] for k in ['authorized_secret_files_read_exact','raw_or_nested_long_string_count','bounded_variant_count','file_count','runtime_secret_variant_hits','literal_marker_numeric_counts_outputs','private_PEM_numeric_counts_outputs','runtime_canary_pass','generic_private_scan_pass','scope_gaps']},'source_build_sql_unchanged':True,'owned_nodes_joined':True,'DB_slots_claims_sessions_zero':True,'mutex_released':True,'verification_result':'completed checks PASS, unresolved mandatory gates retained','product_acceptance':False,'predecessor_unchanged_green_reuse':'A32 all9 native0 stages via verified raw manifest and exact source120/build73/sql15/current protected dependency path; no canonical/fullPG/unit/physical repeat'})
files={str(p.relative_to(R)):{'bytes':p.stat().st_size,'sha256':sha(p)} for p in R.rglob('*') if p.is_file() and not p.is_symlink() and p.name!='raw-artifact-manifest-a33.json'};write('raw-artifact-manifest-a33.json',{'utc':now(),'run_id':ctx['run_id'],'source_head':ctx['source_head'],'files':files,'exclude':['symlinks/protected node_modules/foreign files/self'],'canary_scope_gap':'postscan final context/receipt/reconciliation/manifest metadata not scanned; full tool transcripts outside scratch not generic private scan'})
print(json.dumps({'terminal_utc':terminal,'elapsed_seconds':elapsed,'file_count':len(files),'file_bytes':sum(v['bytes'] for v in files.values()),'receipt_sha256':sha(R/'terminal-receipt-a33.json'),'raw_manifest_sha256':sha(R/'raw-artifact-manifest-a33.json'),'ownership_sha256':sha(R/'terminal-ownership-a33.json'),'remainder_sha256':sha(R/'mandatory-remainder-a33.json')}))
