from pathlib import Path
import json,hashlib,datetime,subprocess,os,fcntl
r=Path('/tmp/n7-f10-atomic-admission-a31');p=Path('/tmp/n7-f10-restart-fix-20261006-a12/projects/07-cold-email-warmup');now=datetime.datetime.now(datetime.timezone.utc);launch=json.loads((r/'launch.json').read_text());elapsed=(now-datetime.datetime.fromisoformat(launch['ack_utc'])).total_seconds();h=lambda a:hashlib.sha256(a.read_bytes()).hexdigest();objective=json.loads((r/'objective-native-first-quanta.json').read_text());native=json.loads((r/'original-adversarial-a31-terminal.json').read_text());assert native['native_returncode']==0 and native['inputs_unchanged'] and not native['remaining_owned_nodes'] and native['PG']['quiescent'];lock=open('/tmp/codex-heavy-build.lock','rb');fcntl.flock(lock,fcntl.LOCK_EX|fcntl.LOCK_NB);fcntl.flock(lock,fcntl.LOCK_UN);lock.close()
report=f'''# A31 atomic native admission author handoff

RUN_ID: 20261006T090602Z-n7-expanded-mvp-a1. Work unit A31. Launch-SHA256: {h(r/'launch.json')}. Finished-At: {now.isoformat()}.

Verdict: AUTHOR_IMPLEMENTATION_READY_FOR_INDEPENDENT_HIGH_VERIFICATION. This completes the bounded author stage, not F10 acceptance. Overall autonomous work remains owned by /root/n7_sol_coordinator, which must actually launch fresh HIGH verification/corrections.

Frozen revision: db50798a76a97fed75931544f24cd1181ff082d8 on parent 0f0653f010e40122532f6dd446fc1e16937656e8, sole writer /tmp/n7-f10-restart-fix-20261006-a12. Exactly4 runtime sources plus3 existing test files committed. No SQL/schema/fixture/dependency/global controls or main-worktree changes. Pre-existing node_modules remains protected/untracked.

The standalone transport wrapper now delegates to the PoolClient allocation helper; RuntimeStore native admission invokes existing authorizeTransport under the SAME FIRST eligibility transaction and reserves physical IMAP ownership with the canonical durable fair claim. Full capacity commits no selection/turn. Selected typed denied/busy outcomes retain turn and backoff behavior. Claim metadata is private WeakMap state. Each native claim composes its scoped PollWorker/one-use adapter; unused cleanup is restricted to exact registered never-child-bound owners and retains exact proof across release DB failure. Bound slots retain existing child-closure/CAS handling. Store.cancel covers abort after committed admission before callback. No network in transaction, no barrier/queue/TTL reclaim. Ordinary F09 standalone/fullpoll fallback unchanged.

The protocol test removes ONLY the unsupported completed-before-E comparison; literal successful five-second native operations, all5 eligibility/denominator, first A-D and E-before-any-old-second, originaldue/restart/service_seq,20 pages,120s attempt,30s completion and60s selection caps remain. Existing assertion wording adjusted to match the retained independent five-second requirement. New raw objective reconstruction directly checks each FIRST scheduled A-D FETCH response >=5000ms; each corresponding first page is committed scanning/pages2 after priming page1. Server response alone is not asserted to prove child exit: actual3 worker exit/drain records and unchanged exact child lifetime handling are retained.

## Actual focused evidence

Typecheck0; lint0; build0; F10 unit7/7 exit0. Focused PG exit0 verifies competing transactions, fullcapacity no rank/claim change, skewed freedslot selects durable laterdue E before oldsecond, originaldue/restart, oneuse rejection, selected typed denial, real injected SQL failure AFTER reservation rolls back claim+slot+durable ranks, and actual runtime abort-after-COMMIT executes no callback and releases reservations. Separate process competition is evidenced by the actual original native test. Existing independent-tenant regression still requires the HIGH full PG gate.

Original affected native test `native five-second rescans yield fairly to later healthy E across competing worker restart` exited0 without timeout in110784.931ms. All5 denominator retained. First5 selection labels {objective['first_five_selection_labels']}; first A-D scheduled native elapsedMs {[x['elapsedMs'] for x in objective['first_native_quanta']]}; literal A-D pages {objective['all_four_pages']}; E first complete {objective['first_E_completion_ms']}ms; largest healthy E complete gap {objective['E_fullpoll_max_gap_ms']}ms. Actual3 joins code0/drained=true; maximum4 IMAP sockets;102 physical acquisitions/102 releases,102 turns/selections/yields. Raw {objective['raw_path']} SHA {objective['raw_sha']}.

Numeric-only authorized canary: exactly5 assigned secret files, exactly5 runtimefiles checked, matches[0,0,0,0,0]. No secret values printed. Existing source canary markers untouched. Complete-source-build-sql-manifest-v2.json SHA {h(r/'complete-source-build-sql-manifest-v2.json')} binds exact120 source/test,73 buildJS,15 SQL. Earlier source-build-freeze.json guessed migrations path and records SQL0; superseded for SQL completeness by this explicit db/15 binding, not erased.

Prelaunch ready receipt binds source/build/fixture/runner/guard, commands, numericlocal network policy, owned n7f10_a2 current_database, quiescence,mutex,disk. Actual native launch PID3561445 ticks124729205 at22:04:42.051189UTC; runner3561286. Terminal22:06:33.021138UTC shows inputs/runner unchanged, no owned nodes, DBquiescent. Shared heavy mutex availability verified nonblocking at seal; no cleanup of protected files, no orphan reclaim. Native test confirmed0 occupied transport rows after joined cleanup.

## Preserved failures and remaining mandatory AC

Original focused PG exit1 was test comparison of unordered row sets; raw pg.log retained. Only ORDER BY fixed, plus substantive actual abort-after-COMMIT witness added; affected type/lint/PG rerun into fresh -v2 artifacts passed. Initial inherited env DATABASE_NAME=n7f09_a1 was rejected before PG/reset, preserved preflight-inherited-db-rejection.txt; explicit authorized n7f10_a2 override succeeded. Default bwrap mkdir .codex failure occurred before execution; authorized narrow escalation used. A29 literal19-versus20 failure cause remains historically UNKNOWN; this new literal20 PASS is not a retrospective shared-cause assertion or waiver.

Coordinator must now launch clean-context independent gpt-6.1-sol HIGH from A30 approved planner report/context/normative14pack/UID contract and this frozen source/tests/raw outcomes, without author chat or working notes. Required gates remain: independent semantic review, full unit/PG regressions, exact positive affected protocol titles (compiled healthy2poll/UIDretry/native ambiguous/SIGSTOP120restart), F09 standalone/captured-fence/closure-fault/staleCAS witnesses, frozen330s 100connected/30active/>=3tenant all30 cadence/restart/fault pool300s, exact physicalSIGSTOP120 and closure/CAS, material split-admission/oneuse/unused-cleanup/bound-release/service_seq/fence mutations and canary. No AC waived; no F10 accepted claim; no external provider/deploy/expense permission added.

Profile model-routing-econom. Requested gpt-6.1-sol/medium. Actual model/effort/input/cache/output/reasoning/cost NULL because host authoritative counters absent. Elapsed author stage {elapsed:.3f}s including instructions, implementation, failed check correction and native verification. Mechanical ROUTE actualS/exit0 (exact4files); substantive L because global admission/child ownership; prior plan approved and independent HIGH mandatory. Savings not established. No delegation by author. No active owned child/mutex/DB process remains at handoff. Next executor must be actually launched by coordinator; terminal author stage does not pause overall autonomous task.

Status: completed
'''
(r/'report.md').write_text(report)
manifest={'finished_at':now.isoformat(),'elapsed_seconds':elapsed,'revision':'db50798a76a97fed75931544f24cd1181ff082d8','run_id':launch['run_id'],'launch_sha256':h(r/'launch.json'),'report_sha256':h(r/'report.md'),'requested_model':'gpt-6.1-sol','requested_effort':'medium','actual_model':None,'actual_effort':None,'usage':None,'cost':None,'stage':'author_completed','product_accepted':False,'next_owner':'/root/n7_sol_coordinator','remaining':'fresh independent HIGH full gates in report','evidence':{a.name:h(a) for a in r.iterdir() if a.is_file() and a.name not in ['report.md','seal-a31.py']},'joins':native,'heavy_mutex_released':True,'no_author_processes_remaining':True};(r/'receipt.json').write_text(json.dumps(manifest,indent=2)+'\n');print('TERMINAL',now.isoformat(),'elapsed',elapsed,'report_sha',h(r/'report.md'),'receipt_sha',h(r/'receipt.json'))
