from pathlib import Path
import json,hashlib,datetime,importlib.util,fcntl,subprocess,os,re
R=Path('/tmp/n7-f10-uid-material-verify-a36');S=R/'compact-shadow-a36';A=Path('/tmp/n7-f10-cancel-diagnostic-a34');sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat();write=lambda n,x:(R/n).write_text(json.dumps(x,indent=2)+'\n');ctx=json.loads((R/'launch-actual.json').read_text());spec=importlib.util.spec_from_file_location('nr',R/'native-run-a36.py');nr=importlib.util.module_from_spec(spec);spec.loader.exec_module(nr);assert not nr.nodes();results=json.loads((R/'uid-material-results-a36.json').read_text());fresh=json.loads((R/'freshness-results-a36.json').read_text());assert len(results)==12 and len(fresh)==2;assert all(x['status']=='caught_material_assertion' for x in results+fresh);alltap={sha(p):p for p in R.glob('*.tap')};rows=[]
for e in results+fresh:
 for stage in ['baseline','negative','restored']:
  x=e[stage];assert not x['timed_out'] and x['native_exit']==(1 if stage=='negative' else 0);tap=alltap[x['tap_sha256']];text=tap.read_text();assert '# tests 1\n' in text;assert x['owned_nodes']==[] and x['PG']['quiescent'];assert x['DB_slots_claims_after_join']['counts']=={'occupied_slots':0,'runtime_claims':0,'other_sessions':0}
  if stage=='negative':assert x['assertion_failure'] and x['failure_titles'];rows.append({'case':e['name'],'native_exit':x['native_exit'],'failure_titles':x['failure_titles'],'tap':str(tap.relative_to(R)),'tap_sha256':sha(tap),'literal_numeric_observers':[l.strip() for l in text.splitlines() if 'A36_' in l],'assertion_fields':[l.strip() for l in text.splitlines() if l.strip().startswith(('expected:','actual:','operator:','code:'))]})
lock=open('/tmp/codex-heavy-build.lock','rb');fcntl.flock(lock,fcntl.LOCK_EX|fcntl.LOCK_NB)
try:
 source=nr.candidate_check();pg=nr.snapshot();db=nr.status();assert pg['quiescent'] and db['counts']=={'occupied_slots':0,'runtime_claims':0,'other_sessions':0};inv=json.loads((R/'shadow-complete-inputs-a36.json').read_text());shadow=[f for f,h in inv.items() if sha(S/f)!=h];assert not shadow;prev=json.loads((A/'raw-artifact-manifest-a34.json').read_text());assert sha(A/'raw-artifact-manifest-a34.json')=='f7852c01c8b903426843686b5c8e71c1b8825ded2f2a6e8434a14a6e96014696';prevdrift=[f for f,v in prev['files'].items() if sha(A/f)!=v['sha256']];assert not prevdrift
 legacy={str(p):sha(p) for p in [Path('/tmp/n7-f10-cadence-implement-a7/short-native-v2.json'),Path('/tmp/n7-f10-cadence-implement-a7/short-native-v2-drain.json')]};assert list(legacy.values())==['60d07dcb6bcec2d5faa0419f86ccb41fce2997564376df6f25d197f5b4ce1007','3d19f0b8d4ed427ae24293f9d897c17f0165ef5bc6132b2fffbd8af01f663b2a'];head=subprocess.check_output(['git','-C',str(nr.P),'rev-parse','HEAD'],text=True).strip();assert head==ctx['source_head'];write('terminal-ownership-a36.json',{'utc':now(),'candidate_head':head,'source120_build73_sql15_drift':source,'shadow183_drift':shadow,'nodes':nr.nodes(),'PG':pg,'DB':db,'legacy_original_hashes':legacy,'A34_prior_raw_verified_count':len(prev['files']),'A34_prior_artifact_drift':prevdrift,'native_node_sha256':sha(nr.N),'protected_dependency_realpath':str((nr.P/'node_modules').resolve()),'disk_available_bytes':os.statvfs('/').f_bavail*os.statvfs('/').f_frsize,'mutex':'exclusive reacquired for proof, released after receipt'})
finally:fcntl.flock(lock,fcntl.LOCK_UN);lock.close()
write('uid-independent-reconciliation-a36.json',{'utc':now(),'finding':'F10-A35-001 / composite AC007','approved_UID_planner_sha256':'998aeeb0b4c89294d7f196650b759954f3a965f62dacfaf8313d1e5eaf749662','authorized_A35_finding_sha256':'dfaaf15d614ed108a77a2cfe2fac99d107b08b5ba76e9a3570c66d5373a806e0','source_head':ctx['source_head'],'unique_approved_mechanisms':6,'source_compiled_mechanism_records':12,'additional_mechanism5_timestamp_records':2,'all_native_stages':'baseline0 / named ERR_ASSERTION negative1 / restored0; literal one-test counts, exact hashes and PIDs/ticks; cached baseline pointers independently reverified by TAP SHA','original_product_source_and_tests_unchanged':True,'operational_test_copies':'existing full-poll and native30.1s retry title with numeric observer only; compiled copies direct ../dist imports; tiny literal PG tail/cursor observer extracted from existing R1 fixed-tail/retry seam and existing runtimeFixture','required6':['mismatch-as-error','accepting/relabeling old FETCH after generation change','second snapshot in one native quantum','explicit retry fixed-tail/cursor reset','false reset completion and false completed_at freshness','ordinary polling explicit-retry bypass'],'negative_raw_assertions':rows,'old_UID_mutation_evidence_reuse':False,'previous_green_reuse':'all unchanged A32/A33/A34/A35 source-bound gates preserved; no fullPG/unit/canonical330/physical/fairness replay','confirmed_source_defect':None,'durable_product_or_test_fix':None,'next_executor':'same independent A35 finding-only raw reconciliation; coordinator must actually trigger it','product_acceptance':False})
report='''A36 scoped UID material verification PASS; product acceptance pending A35 reconciliation.

Candidate db50798a76a97fed75931544f24cd1181ff082d8 remains immutable. Six approved mechanisms have source and compiled baseline0 / named assertion negative1 / restored0 witnesses. Mechanism five also has independent timestamp-only variants, for fourteen records total.

| Mechanism | Independent negative observation |
|---|---|
| Mismatch as error | paused instead of scanning; authenticated snapshots1/FETCH0 |
| Old FETCH/relabel after generation change | snapshots2/FETCH1 instead of snapshots1/FETCH0 |
| Second snapshot in a quantum | native EXAMINE total3 instead of2 after unchanged30.1s retry delay |
| Retry fixed tail/cursor reset | tailNULL/cursor0 instead of literal tail30/cursor20; original horizon10/same run/attempt2 retained in observer |
| False freshness/reset success | scan_complete true instead of false; timestamp-only source/compiled negatives advance completed_at instead of preserving it |
| Explicit retry bypass | ordinary held full poll completes and sends12 extra verbs instead of rescan_incomplete/zero I/O |

Exact assertion/TAP hashes, source/compiled mutations, original/restored module digests, actual native PIDs/startticks/joins and fixture observations are in uid-independent-reconciliation-a36.json and the frozen command manifests. All restored native exits are0, with no timeout/import/compiler/anchor failure counted as material success.

No candidate/main/legacy/source/test/dependency/schema/global changes. Terminal source120/build73/SQL15 and original shadow183 match; owned nodes joined; DB slots/claims/sessions zero; mutex released. Existing greens remain unchanged and no whole healthy replay was run. Runtime canary and literal private-PEM scope are bounded and retain postscan metadata/tool-transcript gaps.

This operational phase supplies the missing witnesses. Same independent A35 finding-only reconciliation remains the required acceptance gate; no source defect or durable fix is claimed. Requested gpt-6.1-sol/high, actual model/effort/usage/cost unavailable/null. Consolidated context metadata was recorded after initial childlaunch; launch/command/guard/shadow manifests preceded it and that timing gap is explicit.
''';(R/'report-a36.md').write_text(report)
subprocess.run(['python3',str(R/'canary-a36.py')],check=True,env=os.environ);canary=json.loads((R/'canary-result-a36.json').read_text());assert canary['runtime_canary_pass'] and canary['generic_private_scan_pass'];terminal=now();elapsed=(datetime.datetime.fromisoformat(terminal)-datetime.datetime.fromisoformat(ctx['actual_ack_utc'])).total_seconds();assert elapsed<1200;write('final-context-a36.json',{**ctx,'terminal_utc':terminal,'elapsed_seconds':elapsed,'verification_result':'scoped six UID material mechanisms PASS; A35 reconciliation pending','product_acceptance':False})
write('terminal-receipt-a36.json',{'utc':terminal,'run_id':ctx['run_id'],'source_head':ctx['source_head'],'profile':'model-routing-econom','requested_model':'gpt-6.1-sol','requested_effort':'high','actual_model':None,'actual_effort':None,'usage':None,'cost':None,'elapsed_seconds':elapsed,'finding':'F10-A35-001 / compositeAC007','unique_mechanisms_pass':6,'unique_mechanisms_required':6,'source_compiled_records':12,'additional_same_mechanism5_timestamp_records':2,'all_native_exits':'baseline0 / named material negative1 / restored0','timeouts_or_import_compile_failures_counted_caught':0,'source120_build73_sql15_unchanged':True,'shadow183_restored':True,'owned_nodes_joined':True,'DB_slots_claims_sessions_zero':True,'mutex_released':True,'ownership_sha256':sha(R/'terminal-ownership-a36.json'),'reconciliation_sha256':sha(R/'uid-independent-reconciliation-a36.json'),'report_sha256':sha(R/'report-a36.md'),'canary_sha256':sha(R/'canary-result-a36.json'),'canary':{k:canary[k] for k in ['authorized_secret_files_read_exact','raw_or_nested_long_string_count','bounded_variant_count','file_count','runtime_secret_variant_hits','literal_marker_numeric_counts_outputs','private_PEM_numeric_counts_outputs','runtime_canary_pass','generic_private_scan_pass','scope_gaps']},'confirmed_source_defect':None,'next_required_executor':'coordinator actually triggers same independent A35 finding-only reconciliation of frozen/raw six witnesses','product_acceptance':False})
files={str(p.relative_to(R)):{'bytes':p.stat().st_size,'sha256':sha(p)} for p in R.rglob('*') if p.is_file() and not p.is_symlink() and p.name!='raw-artifact-manifest-a36.json'};write('raw-artifact-manifest-a36.json',{'utc':now(),'run_id':ctx['run_id'],'source_head':ctx['source_head'],'files':files,'exclude':['symlinks/protected node_modules/foreign files/self'],'canary_scope_gap':'postscan terminal context/receipt/manifest metadata unscanned; tool transcripts outside own artifacts are not a generic private scan'});print(json.dumps({'terminal_utc':terminal,'elapsed_seconds':elapsed,'file_count':len(files),'file_bytes':sum(v['bytes'] for v in files.values()),'receipt_sha256':sha(R/'terminal-receipt-a36.json'),'manifest_sha256':sha(R/'raw-artifact-manifest-a36.json'),'ownership_sha256':sha(R/'terminal-ownership-a36.json'),'reconciliation_sha256':sha(R/'uid-independent-reconciliation-a36.json'),'report_sha256':sha(R/'report-a36.md')}))
