import fs from 'node:fs';
import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const fixture=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));const out=process.argv[3];fs.mkdirSync(out,{recursive:true});
const {base,host}=fixture;const report={started_at:new Date().toISOString(),binding:'Production w.js/config/events; actual network proxy ask -> test-only real handler/PaidGateway/PG with deterministic FakeProvider; no request fulfillment, no paid calls',source:fixture.source_revision,image:fixture.image,checks:[],screenshots:[]};
const browser=await chromium.connect('ws://127.0.0.1:9320');const contexts=[];
async function stats(context,id){return (await context.request.get(`${host}/stats?bot=${id}`)).json();}
async function poll(fn){for(let i=0;i<40;i++){if(await fn())return;await new Promise(r=>setTimeout(r,100));}throw Error('poll timeout');}
try{
 for(const width of [1440,390]){
  const context=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width,height:900}});contexts.push(context);await context.addCookies([{name:'credential-probe',value:'must-not-be-sent',url:base,secure:true,sameSite:'None'}]);const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  const seed=async mode=>(await (await context.request.post(`${host}/seed`,{data:{mode}})).json());
  const free=await seed('free');const csp=[];await page.addInitScript(()=>{window.__csp=[];document.addEventListener('securitypolicyviolation',e=>window.__csp.push(e.violatedDirective));});
  // Delay config transport only; response remains real network/production handler.
  await page.route('**/api/widget/config?**',async route=>{await new Promise(r=>setTimeout(r,250));await route.continue();});
  const responses=[];page.on('response',r=>{if(r.url().includes('/api/widget/ask'))responses.push({status:r.status(),method:r.request().method(),headers:r.headers()});});
  await page.goto(`${host}/?bot=${free.publicId}`);const root=page.locator('n6b-widget');await root.waitFor();assert.equal(await root.getByLabel('Ваш вопрос').isDisabled(),true);await poll(async()=>!(await root.getByLabel('Ваш вопрос').isDisabled()));const badge=root.getByRole('link',{name:'Работает на N6b'});assert.equal(await badge.isVisible(),true);
  const shot=async name=>{const file=`${name}-${width}.png`;await page.screenshot({path:`${out}/${file}`,fullPage:true});report.screenshots.push(file);};await shot('collapsed');
  await poll(async()=> (await stats(context,free.publicId)).events.some(e=>e.kind==='impression'&&e.n===1));
  await badge.evaluate(el=>el.remove());await poll(()=>root.getByRole('link',{name:'Работает на N6b'}).isVisible());await root.getByRole('link',{name:'Работает на N6b'}).evaluate(el=>el.style.setProperty('display','none','important'));await poll(()=>root.getByRole('link',{name:'Работает на N6b'}).isVisible());
  await root.getByRole('button',{name:'Открыть чат'}).click();await root.getByText('Вопросы обрабатывает внешняя модель через OpenRouter (OpenAI). Не сообщайте персональные данные',{exact:true}).waitFor();await root.getByLabel('Ваш вопрос').fill('Когда доставка?');const answerWait=page.waitForResponse(r=>r.url().includes('/api/widget/ask')&&r.request().method()==='POST');await root.getByRole('button',{name:'Отправить',exact:true}).click();assert.equal(await root.getByLabel('Ваш вопрос').isDisabled(),true);const answered=await answerWait;assert.equal(answered.status(),200);assert.equal(answered.headers()['access-control-allow-origin'],host);assert.equal(answered.headers()['access-control-allow-credentials'],undefined);await root.getByText('Доставка 2 дня.',{exact:false}).first().waitFor();assert.ok(await root.locator('a[href="https://site.example/delivery"]').count()===1 || await root.locator('.messages a').count()===1);await shot('answered');
  await root.getByRole('link',{name:'Работает на N6b'}).evaluate(el=>el.hidden=true);await poll(()=>root.getByRole('link',{name:'Работает на N6b'}).isVisible());await root.getByRole('button',{name:'Закрыть',exact:true}).click();assert.equal(await root.getByRole('link',{name:'Работает на N6b'}).isVisible(),true);
  const st=await stats(context,free.publicId);assert.ok(st.requests.some(r=>r.method==='OPTIONS'&&r.status===204&&r.acao===host));assert.ok(st.requests.every(r=>!r.cookiePresent&&r.credentials===null));assert.equal(st.events.find(e=>e.kind==='impression').n,1);assert.ok(st.events.find(e=>e.kind==='tamper').n>=3);assert.ok(st.installs[0].first_question_at);assert.equal(await page.locator('#host-marker').evaluate(el=>getComputedStyle(el).fontSize),'22px');assert.equal(await root.locator('.root').evaluate(el=>getComputedStyle(el).fontSize),'14px');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(await page.evaluate(()=>window.__csp),[]);
  const denied=await context.request.post(`${base}/api/widget/ask?bot=${free.publicId}`,{headers:{Origin:'https://denied-host.test'},data:{bot:free.publicId,question:'x'}});assert.equal(denied.status(),403);assert.equal(denied.headers()['access-control-allow-origin'],undefined);assert.equal((await stats(context,free.publicId)).providerCalls,st.providerCalls);
  const paid=await seed('paid');await page.goto(`${host}/?bot=${paid.publicId}`);await poll(async()=>!(await page.locator('n6b-widget').getByLabel('Ваш вопрос').isDisabled()));assert.equal(await page.locator('n6b-widget .badge').count(),0);assert.deepEqual((await stats(context,paid.publicId)).events,[]);await shot('paid');
  const unknown=await seed('unknown');await page.goto(`${host}/?bot=${unknown.publicId}`);await root.getByRole('button',{name:'Открыть чат'}).click();await poll(async()=>!(await root.getByLabel('Ваш вопрос').isDisabled()));await root.getByLabel('Ваш вопрос').fill('Что неизвестно?');await root.getByRole('button',{name:'Отправить',exact:true}).click();await root.getByText('В материалах сайта нет ответа.',{exact:false}).first().waitFor();await shot('unknown');
  const recover=await seed('recover');await page.goto(`${host}/?bot=${recover.publicId}`);await root.getByRole('button',{name:'Открыть чат'}).click();await poll(async()=>!(await root.getByLabel('Ваш вопрос').isDisabled()));await root.getByLabel('Ваш вопрос').fill('Когда доставка?');const first=page.waitForResponse(r=>r.url().includes('/api/widget/ask')&&r.request().method()==='POST');await root.getByRole('button',{name:'Отправить',exact:true}).click();assert.equal((await first).status(),503);await poll(async()=>!(await root.getByLabel('Ваш вопрос').isDisabled()));const second=page.waitForResponse(r=>r.url().includes('/api/widget/ask')&&r.request().method()==='POST');await root.getByRole('button',{name:'Отправить',exact:true}).click();assert.equal((await second).status(),200);await poll(async()=>!(await root.getByLabel('Ваш вопрос').isDisabled()));
  // Browser reports expected503 network error; no CORS/CSP/JS errors allowed in authorized flows.
  const unexpected=errors.filter(e=>!(e.includes('Failed to load resource')&&e.includes('503')));assert.deepEqual(unexpected,[]);assert.deepEqual(await page.evaluate(()=>window.__csp),[]);report.checks.push({width,pass:true,stats:st,responses,expected_network_errors:errors.filter(e=>e.includes('503'))});await context.close();contexts.splice(contexts.indexOf(context),1);
 }
 report.status='pass';
}catch(error){report.status='failed';report.error=String(error.stack??error);throw error;}finally{report.finished_at=new Date().toISOString();fs.writeFileSync(`${out}/report.json`,JSON.stringify(report,null,2));for(const c of contexts)await c.close();await browser.close();}
