import assert from 'node:assert/strict';
import { test } from 'node:test';
import { fork,spawn,execFileSync } from 'node:child_process';
import { readFile,readdir,writeFile } from 'node:fs/promises';
import { setTimeout as delay } from 'node:timers/promises';
import { cadenceFixture } from './f10-runtime-fixture.js';
import { transportFixture,type TransportBehavior } from './f09-transport-fixture.js';
test('persistent fair workers serve every eligible mailbox',{timeout:400000},async()=>{
  const cli=spawn(process.execPath,['dist/runtime/worker.js'],{cwd:new URL('..',import.meta.url),env:{...process.env,POLL_MODE:'disabled',DISPATCH_MODE:'disabled'},stdio:['ignore','pipe','pipe']});let cliErr='';cli.stderr.on('data',b=>{cliErr+=b.toString();});await new Promise<void>(r=>cli.once('exit',()=>r()));assert.equal(cliErr,'');
 let delayTurn=0;const c=await cadenceFixture(),behavior:TransportBehavior={uidNext:1,headers:[],imapDelayMs:()=>[0,40,120][delayTurn++%3]!},f=await transportFixture(behavior);
 const cpuEnded:number[]=[];let latestDrain:{drained?:boolean;stat?:string}|undefined;const drainOutcomes:unknown[]=[];
 const selections=new Map<string,number[]>(),completions=new Map<string,number[]>(),poolTurns=new Map<string,number[]>(),resources:unknown[]=[],phaseEvents:unknown[]=[];
 let child:ReturnType<typeof fork>|undefined,stdout='',stderr='',drainMs=0,failure:string|null=null;
 const start=async()=>{child=fork(new URL('./f10-runtime-process-fixture.ts',import.meta.url),[],{execArgv:[],stdio:['ignore','pipe','pipe','ipc'],serialization:'advanced'});latestDrain=undefined;child.on('message',m=>{if((m as {drained?:boolean}).drained)latestDrain=m as {drained?:boolean;stat?:string};});child.stdout?.on('data',b=>{stdout+=b.toString();});child.stderr?.on('data',b=>{stderr+=b.toString();});const allowed=(await readFile('/proc/self/status','utf8')).match(/Cpus_allowed_list:\s+(\S+)/)![1]!;const cpuIds=allowed.split(',').flatMap(part=>{const [lo,hi]=part.split('-').map(Number);return Array.from({length:(hi??lo!)-lo!+1},(_,i)=>lo!+i);}).slice(0,2);execFileSync('taskset',['-pc',cpuIds.join(','),String(child.pid)],{stdio:'ignore'});const ready=new Promise<void>((resolve,reject)=>{child!.once('message',m=>{if((m as {started?:boolean}).started)resolve();else reject(new Error('fixture_start_failed'));});child!.once('error',reject);});child.send(f.options);await ready;};
 const stop=async()=>{if(!child)return;const begun=Date.now(),exit=new Promise<{code:number|null;signal:NodeJS.Signals|null}>(r=>child!.once('exit',(code,signal)=>r({code,signal})));child.kill('SIGTERM');const outcome=await exit;drainMs=Math.max(drainMs,Date.now()-begun);if(latestDrain?.stat){const ticks=latestDrain.stat.split(') ')[1]!.split(' ').slice(11,15).map(Number);cpuEnded.push(ticks.reduce((sum,t)=>sum+t,0));}drainOutcomes.push({at:Date.now(),elapsedMs:Date.now()-begun,...outcome,drained:latestDrain?.drained??false});assert.equal(outcome.code,0);assert.equal(outcome.signal,null);assert.equal(latestDrain?.drained,true);};
 const add=(map:Map<string,number[]>,id:string,time:number)=>{const values=map.get(id)??[];if(values.at(-1)!==time)values.push(time);map.set(id,values);};
 const begun=Date.now();let restarted=false,faulted=false,restored=false;
 try{
  await start();
  while(Date.now()-begun<330000){
   const rows=(await c.pool.query("SELECT d.mailbox_id,d.kind,d.last_served_at,p.completed_at,d.reason,d.due_at FROM runtime_due d LEFT JOIN mailbox_poll p ON p.mailbox_id=d.mailbox_id WHERE d.mailbox_id=ANY($1::uuid[])",[c.active])).rows;
   for(const r of rows){if(r.last_served_at&&r.kind==='poll')add(selections,r.mailbox_id,r.last_served_at.getTime());if(r.last_served_at&&r.kind==='pool')add(poolTurns,r.mailbox_id,r.last_served_at.getTime());if(r.completed_at)add(completions,r.mailbox_id,r.completed_at.getTime());}
   if(child?.pid){const pids:number[]=[];const visit=async(pid:number)=>{pids.push(pid);try{const children=(await readFile(`/proc/${pid}/task/${pid}/children`,'utf8')).trim().split(/\s+/).filter(Boolean).map(Number);for(const id of children)await visit(id);}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT'&&(error as NodeJS.ErrnoException).code!=='ESRCH')throw error;}};await visit(child.pid);let ticks=cpuEnded.reduce((sum,n)=>sum+n,0),rssKb=0,fds=0;const processes:unknown[]=[];for(const pid of pids){try{const fields=(await readFile(`/proc/${pid}/stat`,'utf8')).split(') ')[1]!.split(' '),cpu=fields.slice(11,pid===child.pid?15:13).map(Number).reduce((sum,n)=>sum+n,0),status=await readFile(`/proc/${pid}/status`,'utf8'),rss=Number(/VmRSS:\s+(\d+)/.exec(status)?.[1]??0),fd=(await readdir(`/proc/${pid}/fd`)).length;ticks+=cpu;rssKb+=rss;fds+=fd;processes.push({pid,cpuTicks:cpu,rssKb:rss,fds:fd});}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT'&&(error as NodeJS.ErrnoException).code!=='ESRCH')throw error;}}resources.push({at:Date.now(),pid:child.pid,cpuTicksAggregate:ticks,cpuClockTicksPerSecond:Number(execFileSync('getconf',['CLK_TCK'],{encoding:'utf8'}).trim()),rssKbAggregate:rssKb,fdsAggregate:fds,processes,sockets:f.sockets.size,operations:Object.fromEntries(f.verbs.reduce((m:Map<string,number>,verb)=>m.set(verb,(m.get(verb)??0)+1),new Map())),dueAges:rows.map(r=>({id:r.mailbox_id,kind:r.kind,ageMs:Date.now()-r.due_at.getTime(),reason:r.reason})),reasons:Object.fromEntries(rows.reduce((map:Map<string,number>,r)=>map.set(r.kind+':'+r.reason,(map.get(r.kind+':'+r.reason)??0)+1),new Map())),slots:Number((await c.pool.query('SELECT count(*) FROM transport_operation WHERE operation IS NOT NULL')).rows[0].count)});}
   if(!faulted&&Date.now()-begun>90000){behavior.uidvalidity='2';behavior.uidNext=2;behavior.taggedFailure='NO';faulted=true;phaseEvents.push({phase:'fault',at:Date.now()});}
   if(faulted&&!restored&&Date.now()-begun>120000){behavior.taggedFailure=undefined;restored=true;const {ReplyStore}=await import('../src/replies/store.js');const {identity}=await import('../src/replies/worker.js');const paused=(await c.pool.query("SELECT tenant_id,mailbox_id FROM reply_rescan WHERE state='rescan_incomplete'")).rows;const operator=new ReplyStore(c.pool,c.config.credentialKeyring);for(const r of paused){const run=await operator.status(r.tenant_id,r.mailbox_id);if(run)await operator.retry(r.tenant_id,r.mailbox_id,identity(run));}phaseEvents.push({phase:'explicit_fixture_operator_retry',count:paused.length,at:Date.now()});phaseEvents.push({phase:'fault_restored',at:Date.now()});}
   if(!restarted&&Date.now()-begun>150000){await stop();const held=(await c.pool.query("SELECT tenant_id,mailbox_id FROM reply_rescan WHERE state='rescan_incomplete'")).rows;const {ReplyStore}=await import('../src/replies/store.js');const {identity}=await import('../src/replies/worker.js');const operator=new ReplyStore(c.pool,c.config.credentialKeyring);for(const r of held){const run=await operator.status(r.tenant_id,r.mailbox_id);if(run)await operator.retry(r.tenant_id,r.mailbox_id,identity(run));}phaseEvents.push({phase:'explicit_fixture_operator_retry_after_drain',count:held.length,at:Date.now()});await start();restarted=true;phaseEvents.push({phase:'restart',at:Date.now(),drainMs});}
   await delay(500);
  }
  await stop();
  const gap=(values:number[])=>values.length<2?null:Math.max(...values.slice(1).map((v,i)=>v-values[i]!));
  const receipt={begun,ended:Date.now(),phaseEvents,drainMs,drainOutcomes,peerLatencies:f.peerLatencies,fixtureMaxConnections:f.maxConnections,resources,perMailbox:c.active.map(id=>({id,selected:selections.get(id)??[],completed:completions.get(id)??[],pool:poolTurns.get(id)??[],maxSelectionGap:gap(selections.get(id)??[]),maxCompletionGap:gap(completions.get(id)??[]),maxPoolGap:gap(poolTurns.get(id)??[])})),stdout,stderr};
  await writeFile(`${process.env.F10_EVIDENCE_DIR??'/tmp/n7-f10-cadence-implement-a7'}/cadence-${begun}.json`,JSON.stringify(receipt,null,2)+'\n');
  assert.equal(receipt.perMailbox.length,30);assert.ok(f.verbs.includes('UID'),'fault fixture must execute FETCH');assert.ok(phaseEvents.some(e=>(e as {phase:string;count?:number}).phase==='explicit_fixture_operator_retry'&&((e as {count?:number}).count??0)>0),'fault must pause and require explicit retry');assert.ok(drainMs<=15000);assert.ok(f.maxConnections<=6);
  const restartAt=(phaseEvents.find(e=>(e as {phase:string}).phase==='restart') as {at:number}).at;
  const checkWindow=(values:number[],start:number,end:number,bound:number,label:string)=>{const inside=values.filter(t=>t>=start&&t<=end);assert.ok(inside.length>=2,`${label} missing completions/selections`);assert.ok(inside[0]!-start<=bound,`${label} first deadline ${inside[0]!-start}`);assert.ok((gap(inside)??Infinity)<=bound,`${label} gap ${gap(inside)}`);assert.ok(end-inside.at(-1)!<=bound,`${label} censored tail ${end-inside.at(-1)!}`);};
  for(const row of receipt.perMailbox){checkWindow(row.completed,restartAt,receipt.ended,30000,`${row.id} postrestart completions`);checkWindow(row.selected,restartAt,receipt.ended,60000,`${row.id} postrestart selections`);}
  for(const row of receipt.perMailbox){assert.ok(row.completed.length>=2,`mailbox ${row.id} never completed twice`);const healthy=row.completed.filter(t=>t<begun+90000);assert.ok(healthy.length>=2);assert.ok((gap(healthy)??Infinity)<=30000,`mailbox ${row.id} healthy completion gap ${gap(healthy)}`);assert.ok((gap((selections.get(row.id)??[]).filter(t=>t<begun+90000))??Infinity)<=60000);assert.ok(row.pool.length>=2);assert.ok((gap(row.pool)??Infinity)<=300000);}
 }catch(error){failure=error instanceof Error?error.message:String(error);throw error;}finally{await writeFile(`${process.env.F10_EVIDENCE_DIR??'/tmp/n7-f10-cadence-implement-a7'}/cadence-partial-${begun}.json`,JSON.stringify({begun,ended:Date.now(),failure,phaseEvents,drainMs,drainOutcomes,peerLatencies:f.peerLatencies,fixtureMaxConnections:f.maxConnections,resources,selections:Object.fromEntries(selections),completions:Object.fromEntries(completions),poolTurns:Object.fromEntries(poolTurns),stdout,stderr},null,2)+'\n');if(child?.exitCode===null&&child.signalCode===null){child.kill('SIGKILL');await new Promise(r=>child!.once('exit',r));}await f.close();await c.pool.end();}
});
