import assert from 'node:assert/strict';
import { test } from 'node:test';
import { submitSmtp } from '../src/dispatch/smtp.js';
import { renderLiveMessage } from '../src/dispatch/message.js';
import type { ReadResult } from '../src/replies/adapter.js';
import { imapRead,imapSnapshot } from '../src/replies/imap.js';
import { transportFixture,transportInput,transportAllowlist } from './f09-transport-fixture.js';
const pageOf=(result:ReadResult)=>{assert.equal(result.kind,'page');assert.ok(result.kind==='page');return result.page;};
const message=()=>renderLiveMessage('a@example.com','b@example.com',{subject:'Привет',body:'Body'},'http://127.0.0.1').message;
test('pinned SMTP accepts only the final DATA completion',async()=>{for(const smtpPort of [465,587] as const){const f=await transportFixture();try{assert.equal((await submitSmtp({...transportInput,smtpPort},message(),transportAllowlist,new AbortController().signal,f.connector)).kind,'accepted');assert.equal(f.verbs.filter(v=>v==='DATA').length,1);if(smtpPort===587)assert.equal(f.verbs.filter(v=>v==='EHLO').length,2);}finally{await f.close();}}});
test('post DATA uncertainty never retries or releases quota',async()=>{for(const behavior of [{disconnectAfterData:true},{finalCode:450},{finalCode:550},{finalCode:251}]){const f=await transportFixture(behavior);try{const r=await submitSmtp(transportInput,message(),transportAllowlist,new AbortController().signal,f.connector);assert.equal(r.kind,behavior.finalCode===450||behavior.finalCode===550?'rejected_after_data':'ambiguous');assert.equal(f.verbs.filter(v=>v==='DATA').length,1);assert.ok(!JSON.stringify(r).includes('CANARY'));}finally{await f.close();}}});
test('IMAP proves bounded read only UID range coverage',async()=>{const f=await transportFixture({uidNext:1000,headers:[{uid:42,text:'From: b@example.com\r\nMessage-ID: <reply@example.com>\r\n\r\n'}]});try{const snapshot=await imapSnapshot(transportInput,transportAllowlist,new AbortController().signal,f.connector);assert.equal(snapshot.uidvalidity,'1');const page=pageOf(await imapRead(transportInput,transportAllowlist,'1',0,999,new AbortController().signal,f.connector));assert.equal(page.coveredThrough,100);assert.equal(page.headers[0]?.uid,42);assert.ok(f.verbs.includes('EXAMINE'));assert.ok(!f.verbs.some(v=>['SELECT','STORE','APPEND'].includes(v)));const fetches=f.verbs.filter(v=>v==='UID').length;const reset=await imapRead(transportInput,transportAllowlist,'2',0,999,new AbortController().signal,f.connector);assert.equal(reset.kind,'uidvalidity_changed');assert.ok(reset.kind==='uidvalidity_changed');assert.equal(reset.snapshot.uidvalidity,'1');assert.equal(reset.snapshot.uidNext,1000);assert.equal(reset.snapshot.provenance,'imap_headers');assert.equal(f.verbs.filter(v=>v==='UID').length,fetches);}finally{await f.close();}});
test('hostile framing and cancellation release bounded resources',async()=>{for(const behavior of [{wrongTag:true},{oversizeLiteral:true}]){const f=await transportFixture({...behavior,headers:[{uid:1,text:'From: b@example.com\r\n\r\n'}]});try{await assert.rejects(imapRead(transportInput,transportAllowlist,'1',0,1,new AbortController().signal,f.connector));}finally{await f.close();}}const f=await transportFixture({stall:true});try{const c=new AbortController(),pending=submitSmtp(transportInput,message(),transportAllowlist,c.signal,f.connector);setTimeout(()=>c.abort(),30);assert.equal((await pending).kind,'permanent');await new Promise(r=>setTimeout(r,25));assert.equal(f.sockets.size,0);}finally{await f.close();}});
test('transport secrets and fixture authority remain isolated',async()=>{const f=await transportFixture();let dials=0;try{const result=await submitSmtp(transportInput,message(),transportAllowlist,new AbortController().signal,{...f.connector,resolver:async()=>[{address:'127.0.0.1',family:4}],dial:()=>{dials++;throw new Error();}});assert.equal(result.kind,'permanent');assert.equal(dials,0);assert.ok(!JSON.stringify(result).includes('CANARY'));}finally{await f.close();}});
test('fragmented literals numeric gaps empty tails and exact byte bounds fail closed',async()=>{
 for(const rev2 of [false,true]){const base='From: b@example.com\r\nReferences: <parent@example.com>\r\n\r\n',f=await transportFixture({rev2,uidNext:2,fragmentBytes:1,headers:[{uid:1,text:base}]});try{const p=pageOf(await imapRead(transportInput,transportAllowlist,'1',0,1,new AbortController().signal,f.connector));assert.equal(p.headers[0]?.uid,1);const tail=pageOf(await imapRead(transportInput,transportAllowlist,'1',1,1,new AbortController().signal,f.connector));assert.equal(tail.coveredThrough,1);assert.equal(tail.headers.length,0);}finally{await f.close();}}
 const fixed='From:  <b@example.com>\r\n\r\n',text=fixed.replace('  <',' '+'A'.repeat(8192-Buffer.byteLength(fixed))+' <');assert.equal(Buffer.byteLength(text),8192);
 const f=await transportFixture({headers:[{uid:1,text}]});try{assert.equal(pageOf(await imapRead(transportInput,transportAllowlist,'1',0,1,new AbortController().signal,f.connector)).headers.length,1);}finally{await f.close();}
 for(const behavior of [{headers:[{uid:1,text:'From: b@example.com\r\n\r\na4 OK complete\r\n'}]},{headers:[{uid:1,text:fixed},{uid:1,text:fixed}]},{headers:[{uid:1,text:fixed}],taggedFailure:'NO'},{headers:[{uid:1,text:fixed}],fetchSuffix:' UID 2)'},{headers:[{uid:1,text:fixed}],fetchPrefix:'* 1 FETCH (BODY[HEADER.FIELDS (FROM MESSAGE-ID IN-REPLY-TO REFERENCES)] {26}\r\n'},{headers:[{uid:1,text:fixed}],fetchPrefix:'* 1 FETCH (UID 99 BODY[HEADER.FIELDS (FROM MESSAGE-ID IN-REPLY-TO REFERENCES)] {26}\r\n'}]){const peer=await transportFixture(behavior);try{await assert.rejects(imapRead(transportInput,transportAllowlist,'1',0,1,new AbortController().signal,peer.connector));}finally{await peer.close();}}
});
test('write drain TLS hostname receive limits and cleanup use actual sockets',async()=>{
 const {TransportBudget,TransportChannel}=await import('../src/mailboxes/transport-channel.js'),f=await transportFixture({stall:true});try{
  const c=new TransportChannel(new TransportBudget(new AbortController().signal,10000),65536,f.connector);await c.open('smtp.gmail.com',465,transportAllowlist);await c.upgrade('smtp.gmail.com');await c.write(Buffer.alloc(65536,65));assert.ok(c.resources().drainWaits>=1);await c.close();await new Promise(r=>setTimeout(r,10));const resources=c.resources();assert.equal(resources.sockets,0);assert.equal(resources.timers,0);assert.equal(resources.abortListeners,0);assert.equal(resources.queuedBytes,0);assert.equal(resources.listeners,0);
  const wrong={...transportInput,smtpHost:'wrong.example.com'};assert.equal((await submitSmtp(wrong,message(),new Map([...transportAllowlist,['wrong.example.com',30]]),new AbortController().signal,f.connector)).kind,'permanent');
 }finally{await f.close();}
 const giant=await transportFixture({greetingCode:220});try{let dials=0;const connector={...giant.connector,resolver:async()=>[{address:'8.8.8.8',family:4},{address:'10.0.0.1',family:4}],dial:()=>{dials++;throw new Error();}};assert.equal((await submitSmtp(transportInput,message(),transportAllowlist,new AbortController().signal,connector)).kind,'permanent');assert.equal(dials,0);}finally{await giant.close();}
});
test('pre DATA proof post DATA truncated final and acceptance before close remain distinct',async()=>{
 for(const [behavior,kind] of [[{mailCode:450},'pre_data_transient'],[{mailCode:550},'permanent'],[{authCode:535},'permanent'],[{greetingCode:250},'permanent'],[{partialFinal:true},'ambiguous'],[{closeAfterFinal:true},'accepted']] as const){const f=await transportFixture(behavior);try{assert.equal((await submitSmtp(transportInput,message(),transportAllowlist,new AbortController().signal,f.connector)).kind,kind);}finally{await f.close();}}
});
test('receive line bound rejects8193 bytes before peer text is accepted',async()=>{const f=await transportFixture({controlBytes:8187});try{assert.equal((await submitSmtp(transportInput,message(),transportAllowlist,new AbortController().signal,f.connector)).kind,'permanent');}finally{await f.close();}});
for(const phase of ['EHLO','AUTH'] as const)test(`whole SMTP ${phase} challenge phase expires once at ten seconds`,{timeout:15000},async()=>{
 const f=await transportFixture(phase==='EHLO'?{slowEhlo:true}:{slowAuthChallenge:true});try{
  const started=performance.now(),outcome=await submitSmtp(transportInput,message(),transportAllowlist,new AbortController().signal,f.connector),elapsed=performance.now()-started;
  process.stdout.write(JSON.stringify({phase,elapsedMs:elapsed,outcome:outcome.kind,commands:f.verbs})+'\n');
  assert.equal(outcome.kind,'pre_data_transient',phase);if(outcome.kind==='pre_data_transient')assert.equal(outcome.proof,'no_data_submitted');assert.ok(elapsed>=9500&&elapsed<11500,`${phase} total elapsed ${elapsed}`);
  assert.equal(f.verbs.filter(v=>v==='DATA').length,0);assert.equal(f.verbs.filter(v=>v==='MAIL').length,0);if(phase==='EHLO')assert.equal(f.verbs.filter(v=>v==='AUTH').length,0);else assert.equal(f.verbs.filter(v=>v==='AUTH_RESPONSE').length,1);
  await new Promise(r=>setTimeout(r,25));assert.equal(f.sockets.size,0);
 }finally{await f.close();}
});

test('same UID coverage remains fixed while a smaller declared horizon fails',async()=>{
 const f=await transportFixture({uidvalidity:'7',uidNext:1000,headers:[]});try{
  const result=await imapRead(transportInput,transportAllowlist,'7',5,7,new AbortController().signal,f.connector);assert.equal(pageOf(result).coveredThrough,7);
 }finally{await f.close();}
 const smaller=await transportFixture({uidvalidity:'7',uidNext:2,headers:[]});try{await assert.rejects(imapRead(transportInput,transportAllowlist,'7',0,3,new AbortController().signal,smaller.connector));assert.equal(smaller.verbs.filter(v=>v==='UID').length,0);}finally{await smaller.close();}
});
