// Isolated test-only binding: production demo handler/gateway/PG with deterministic provider.
import {createServer} from 'node:http';
import pg from '/app/node_modules/pg/lib/index.js';
import {createDemoHandler} from '/app/apps/web/src/server/demo-handler.ts';
import {constructGateway} from '/app/packages/rag/src/paid-call.ts';
import {AnswerFixtureProvider,AXIS,LIMITS} from '/app/apps/web/tests/int/answer-fixture.ts';
const base=process.env.PUBLIC_BASE_URL!,host='https://demo-host.test';
const owner=new pg.Pool({connectionString:process.env.DATABASE_URL_OWNER});
const service=new pg.Pool({connectionString:process.env.DATABASE_URL_SERVICE});
const fixtures=new Map<string,any>();
function bind(f:any,mode:string){const provider=new AnswerFixtureProvider({delayMs:300,...(mode==='recover'?{outcomes:['unavailable']}:{}),answer:mode==='unknown'?{answer:'ignored',cited_ids:[],unknown:true}:{answer:'Доставка 2 дня. <script>text</script>',cited_ids:[f.chunkId],unknown:false}});f.providers.push(provider);f.handler=createDemoHandler({servicePool:service,publicBaseUrl:base,visitorSecret:process.env.VISITOR_SECRET!,minSimilarity:.7,gateway:constructGateway({pool:service,provider,limits:{...LIMITS,answerVisitorDay:3},visitorSecret:process.env.VISITOR_SECRET!,now:()=>f.now}),now:()=>f.now});}
createServer(async(req,res)=>{try{
 const u=new URL(req.url!,host);if(u.pathname==='/favicon.ico'){res.statusCode=204;res.end();return;}if(u.pathname==='/health'){res.end('ok');return;}
 const chunks:Buffer[]=[];for await(const c of req)chunks.push(c);const bytes=Buffer.concat(chunks);
 const send=(data:any)=>{res.setHeader('content-type','application/json');res.end(JSON.stringify(data));};
 if(u.pathname==='/attach'){const {botId}=JSON.parse(bytes.toString());const b=(await owner.query('SELECT id,account_id FROM bot WHERE id=$1',[botId])).rows[0];if(!b)throw Error('fixture bot missing');const src=(await owner.query('SELECT id FROM source WHERE bot_id=$1 LIMIT 1',[botId])).rows[0];const d=(await owner.query("INSERT INTO document(source_id,account_id,locator_url,title,text,content_sha256) VALUES($1,$2,'https://own.example.test/delivery','<script>Доставка</script>','Доставка 2 дня','ui') RETURNING id",[src.id,b.account_id])).rows[0];const ch=(await owner.query("INSERT INTO chunk(document_id,bot_id,account_id,ord,text,text_sha256,tokens,embedding) VALUES($1,$2,$3,0,'Доставка 2 дня','ui',5,$4) RETURNING id",[d.id,botId,b.account_id,JSON.stringify(AXIS)])).rows[0];const f={botId,accountId:b.account_id,chunkId:ch.id,now:new Date(),providers:[],requests:[]};bind(f,'free');fixtures.set(botId,f);send({attached:true});return;}
 if(u.pathname==='/mode'){const {botId,mode}=JSON.parse(bytes.toString());const f=fixtures.get(botId);if(!f)throw Error('fixture missing');if(mode==='paid')await owner.query("UPDATE account SET plan='start',badge_removal='active' WHERE id=$1",[f.accountId]);else bind(f,mode);send({changed:true});return;}
 if(u.pathname==='/stats'){const f=fixtures.get(u.searchParams.get('bot')!);const logs=(await owner.query('SELECT channel,outcome,count(*)::int AS n FROM question_log WHERE bot_id=$1 GROUP BY channel,outcome',[f.botId])).rows;const installs=(await owner.query('SELECT count(*)::int AS n FROM widget_install WHERE bot_id=$1',[f.botId])).rows[0].n;send({providerCalls:f.providers.reduce((n:number,x:any)=>n+x.total,0),logs,installs,requests:f.requests});return;}
 if(u.pathname==='/'){const slug=u.searchParams.get('slug')??'';if(!/^[A-Za-z0-9_-]{24}$/.test(slug)){res.statusCode=400;res.end();return;}res.setHeader('content-type','text/html;charset=utf-8');res.end(`<!doctype html><html><meta name="viewport" content="width=device-width"><body><h1>Чужой сайт</h1><iframe src="${base}/b/${slug}"></iframe><script>fetch('${base}/api/demo/${slug}/ask',{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:'{"question":"Чужой вопрос"}'}).catch(()=>{});</script></body></html>`);return;}
 const match=u.pathname.match(/^\/api\/demo\/([^/]+)\/ask$/);if(!match){res.statusCode=404;res.end();return;}const b=(await owner.query('SELECT id FROM bot WHERE demo_slug=$1',[match[1]])).rows[0];const f=b?fixtures.get(b.id):null;if(!f){res.statusCode=404;res.end();return;}const headers=new Headers();for(const[k,v]of Object.entries(req.headers))if(v)headers.set(k,Array.isArray(v)?v.join(','):v);const response=await f.handler(new Request(base+req.url,{method:req.method,headers,...(req.method==='POST'?{body:bytes}:{})}),match[1]);f.requests.push({status:response.status,method:req.method,origin:headers.get('origin'),media:headers.get('content-type')});res.statusCode=response.status;response.headers.forEach((v:string,k:string)=>res.setHeader(k,v));res.end(await response.text());
 }catch(e){console.error((e as Error).name);res.statusCode=500;res.end('fixture failure');}}).listen(3001,'0.0.0.0',()=>console.log('demo fixture ready'));
