import fs from 'node:fs';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {chromium} from 'playwright';
const f=JSON.parse(fs.readFileSync(process.argv[2],'utf8')),out=process.argv[3];fs.mkdirSync(out,{recursive:true});
const report={started_at:new Date().toISOString(),source_revision:f.source_revision,image:f.image,source_snapshot_sha256:f.source_snapshot_sha256,binding:'Production Next HTML/cabinet/auth/publication; actual HTTP demo asks to identical frozen handler + real PaidGateway/PostgreSQL with isolated FakeProvider. Fixture visitor cap3, no paid calls, no Playwright routing or fulfilled responses. Source document/chunk seeded into API-created bot; foreign host is test-only ordinary HTTP page.',checks:[],screenshots:[]};
const browser=await chromium.connect('ws://127.0.0.1:9320'),contexts=[];let stage='start';
const poll=async fn=>{for(let i=0;i<60;i++){if(await fn())return;await new Promise(r=>setTimeout(r,100));}throw Error('poll timeout');};
try{for(const width of [1440,390]){
 const context=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width,height:1000}});contexts.push(context);const page=await context.newPage(),errors=[];page.setDefaultTimeout(20000);page.setDefaultNavigationTimeout(20000);page.on('pageerror',e=>errors.push(e.message));
 const shot=async name=>{const file=`${name}-${width}.png`;await page.screenshot({path:out+'/'+file,fullPage:true});report.screenshots.push(file);};
 stage=`register-${width}`;const email=`demo-${width}-${randomUUID()}@example.test`;await page.goto(f.base+'/register');await page.getByLabel('E-mail',{exact:true}).fill(email);await page.getByLabel('Пароль',{exact:true}).fill(f.password);await page.getByRole('button',{name:'Зарегистрироваться',exact:true}).click();await page.waitForURL(f.base+'/cabinet');
 const created=await context.request.post(f.base+'/api/bots',{headers:{Origin:f.base},data:{name:'Демо '+width,site_url:'https://8.8.8.8/demo'}});assert.equal(created.status(),202);const botId=(await created.json()).data.bot_id;
 assert.equal((await context.request.post(f.host+'/attach',{data:{botId}})).status(),200);await page.reload();const pub=page.locator('#publish-'+botId);await pub.getByLabel('Контакт владельца (обязательно)',{exact:true}).fill('owner@example.test');await pub.getByLabel('Разрешённые домены (по одному адресу на строку)',{exact:true}).fill('');await pub.getByLabel('Включить публичную демо-страницу',{exact:true}).check();
 const save=async()=>{const response=page.waitForResponse(r=>r.url().endsWith('/publish')&&r.request().method()==='PATCH');await pub.getByRole('button',{name:'Подтвердить и сохранить публикацию',exact:true}).click();assert.equal((await response).status(),200);await pub.getByRole('status').filter({hasText:'Публикация сохранена.'}).waitFor();};await save();let demoPath=await pub.getByRole('link',{name:'Поделиться демо-страницей',exact:true}).getAttribute('href');assert.match(demoPath,/^\/b\/[A-Za-z0-9_-]{24}$/);const slug=demoPath.slice(3);await page.reload();assert.equal(await pub.getByRole('link',{name:'Поделиться демо-страницей',exact:true}).getAttribute('href'),demoPath);
 stage=`chat-${width}`;const response=await page.goto(f.base+demoPath);assert.equal(response.status(),200);const headers=response.headers();assert.equal(headers['x-robots-tag'],'noindex');assert.ok(headers['cache-control'].includes('no-store'));assert.ok(headers['content-security-policy'].includes("frame-ancestors 'none'"));assert.equal(headers['x-frame-options'],'DENY');await page.getByText('Вопросы обрабатывает внешняя модель через OpenRouter (OpenAI). Не сообщайте персональные данные',{exact:true}).waitFor();assert.equal(await page.getByRole('link',{name:'Создать своего бота',exact:true}).isVisible(),true);await page.waitForLoadState('networkidle');
 const ask=async expected=>{await page.getByLabel('Вопрос (до 500 символов)',{exact:true}).fill('Когда доставка?');const next=page.waitForResponse(r=>r.url()===f.base+'/api/demo/'+slug+'/ask'&&r.request().method()==='POST');await page.getByRole('button',{name:/^(Спросить|Повторить вопрос)$/}).click();assert.equal(await page.getByLabel('Вопрос (до 500 символов)',{exact:true}).isDisabled(),true);const r=await next;assert.equal(r.status(),expected);assert.equal(r.headers()['access-control-allow-origin'],undefined);await poll(async()=>!(await page.getByLabel('Вопрос (до 500 символов)',{exact:true}).isDisabled()));return r;};
 await ask(200);await page.getByText('Доставка 2 дня.',{exact:false}).first().waitFor();assert.equal(await page.locator('a[href="https://own.example.test/delivery"]').count(),1);assert.equal(await page.locator('script').filter({hasText:'text</script>'}).count(),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await shot('answered');
 const stats=async()=>await (await context.request.get(f.host+'/stats?bot='+botId)).json();const before=await stats();assert.equal(before.providerCalls,2);assert.equal(before.installs,0);
 stage=`foreign-${width}`;const foreign=await context.newPage();foreign.setDefaultTimeout(20000);const rejected=foreign.waitForResponse(r=>r.url()===f.base+'/api/demo/'+slug+'/ask'&&r.request().method()==='POST');await foreign.goto(f.host+'/?slug='+slug);assert.equal((await rejected).status(),403);await foreign.waitForTimeout(500);assert.ok(foreign.frames().every(frame=>!frame.url().startsWith(f.base+'/b/')));const after=await stats();assert.equal(after.providerCalls,before.providerCalls);assert.deepEqual(after.logs,before.logs);assert.equal(after.installs,0);await foreign.close();
 stage=`retry-limit-${width}`;assert.equal((await context.request.post(f.host+'/mode',{data:{botId,mode:'recover'}})).status(),200);await ask(503);await page.getByRole('alert').waitFor();await ask(200);await page.getByText('Доставка 2 дня.',{exact:false}).first().waitFor();await ask(429);await page.getByRole('alert').filter({hasText:'owner@example.test'}).waitFor();await shot('limited');
 stage=`paid-${width}`;await context.request.post(f.host+'/mode',{data:{botId,mode:'paid'}});await page.reload();assert.equal(await page.getByRole('link',{name:'Создать своего бота',exact:true}).count(),0);await shot('paid');
 stage=`disable-${width}`;await page.goto(f.base+'/cabinet');await pub.getByLabel('Включить публичную демо-страницу',{exact:true}).uncheck();await save();assert.equal(await pub.getByRole('link',{name:'Поделиться демо-страницей',exact:true}).count(),0);const closed=await page.goto(f.base+demoPath);assert.equal(closed.status(),404);assert.ok(closed.headers()['cache-control'].includes('no-store'));assert.equal(closed.headers()['x-robots-tag'],'noindex');assert.ok(closed.headers()['content-security-policy'].includes("frame-ancestors 'none'"));assert.equal((await context.request.post(f.base+'/api/demo/'+slug+'/ask',{headers:{Origin:f.base},data:{question:'x'}})).status(),404);await shot('disabled');
 await page.goto(f.base+'/cabinet');await pub.getByLabel('Включить публичную демо-страницу',{exact:true}).check();await save();assert.equal(await pub.getByRole('link',{name:'Поделиться демо-страницей',exact:true}).getAttribute('href'),demoPath);const final=await stats();assert.equal(final.installs,0);assert.ok(final.logs.every(x=>x.channel==='demo'));assert.deepEqual(errors,[]);report.checks.push({width,email,botId,slug,registration:true,owner_enable_disable_stable_slug:true,headers,foreign_iframe_blocked:true,simple_post403_without_cost:true,answer200:true,retry503to200:true,limit429_contact:true,paid_badge_hidden:true,no_installs:true,javascript_errors:0,final});await context.close();contexts.splice(contexts.indexOf(context),1);
}report.status='pass';}catch(e){report.status='failed';report.stage=stage;report.error=String(e.stack??e);process.exitCode=1;}finally{report.finished_at=new Date().toISOString();fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));for(const c of contexts)await c.close();await browser.close();console.log(JSON.stringify(report));}
