export function quotaEnvironment() {
  return {
    N5_LIMIT_USER_MINUTES: process.env.N5_LIMIT_USER_MINUTES,
    N5_LIMIT_USER_UPLOADS: process.env.N5_LIMIT_USER_UPLOADS,
    N5_LIMIT_USER_UPLOAD_REFUNDS: process.env.N5_LIMIT_USER_UPLOAD_REFUNDS,
    N5_LIMIT_USER_LLM: process.env.N5_LIMIT_USER_LLM,
    N5_LIMIT_GLOBAL_MINUTES: process.env.N5_LIMIT_GLOBAL_MINUTES,
    N5_LIMIT_GLOBAL_LLM: process.env.N5_LIMIT_GLOBAL_LLM,
  };
}
