import fs from 'node:fs';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const f=JSON.parse(fs.readFileSync(process.argv[2],'utf8')),out=process.argv[3];fs.mkdirSync(out,{recursive:true});
const report={started_at:new Date().toISOString(),source_revision:f.source_revision,source_snapshot_sha256:f.source_snapshot_sha256,image:f.image,binding:'Production web/auth/operator checks/SQL metrics/Next after and safeHTTP. Positive verified counts are seeded isolated DB fixtures, not live public-page acceptance. Pending source-verify.test resolves to private Docker IP and must remain unverified; no SSRF bypass or response mocks.',checks:[],screenshots:[]};
const browser=await chromium.connect('ws://127.0.0.1:9320');const contexts=[];let stage='start';
try {
 for(const width of [1440,390]) {
  const context=await browser.newContext({viewport:{width,height:1000},ignoreHTTPSErrors:true});contexts.push(context);const page=await context.newPage(),errors=[];page.setDefaultTimeout(20000);page.setDefaultNavigationTimeout(20000);page.on('request',r=>{if(r.url().includes('/admin/metrics/verify'))console.log('REQUEST',r.method(),r.url())});page.on('response',r=>{if(r.url().includes('/admin/metrics/verify'))console.log('RESPONSE',r.status())});page.on('pageerror',e=>errors.push(e.message));
  stage=`anonymous-${width}`;assert.equal((await page.goto(f.base+'/admin/metrics')).status(),404);assert.equal((await context.request.post(f.base+'/admin/metrics/verify',{headers:{Origin:f.base}})).status(),404);
  await page.goto(f.base+'/login');await page.getByLabel('E-mail',{exact:true}).fill(f.viewerEmail);await page.getByLabel('Пароль',{exact:true}).fill(f.password);await page.getByRole('button',{name:'Войти',exact:true}).click();await page.waitForURL(f.base+'/cabinet');assert.equal((await page.goto(f.base+'/admin/metrics')).status(),404);assert.equal((await context.request.post(f.base+'/admin/metrics/verify',{headers:{Origin:f.base}})).status(),404);await page.screenshot({path:`${out}/ordinary404-${width}.png`,fullPage:true});report.screenshots.push(`ordinary404-${width}.png`);
  await page.goto(f.base+'/cabinet');await page.getByRole('button',{name:'Выйти',exact:true}).click();await page.waitForURL(f.base+'/login');await page.getByLabel('E-mail',{exact:true}).fill(f.operatorEmail);await page.getByLabel('Пароль',{exact:true}).fill(f.password);await page.getByRole('button',{name:'Войти',exact:true}).click();await page.waitForURL(f.base+'/cabinet');
  stage=`operator-${width}`;console.log(stage);const response=await page.goto(f.base+'/admin/metrics');assert.equal(response.status(),200);assert.ok(response.headers()['cache-control'].includes('no-store'));await page.getByRole('heading',{name:'Метрика недели',exact:true}).waitFor();
  const metrics=async()=>page.locator('dl').evaluate(el=>Object.fromEntries([...el.querySelectorAll('dt')].map(dt=>[dt.textContent,dt.nextElementSibling.textContent])));const expected={'Перепроверенные внешние виджеты (цель 15)':'2 / 15','Без перепроверки (конфиг + вопрос)':'3','Показы бейджа':'10','Клики бейджа':'3','Регистрации с ref':'2','Конверсия клика в регистрацию':'66.67%'};assert.deepEqual(await metrics(),expected);await page.getByText('n < 30, K не считается',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:`${out}/metrics-${width}.png`,fullPage:true});report.screenshots.push(`metrics-${width}.png`);
  stage=`verify-${width}`;console.log(stage);await page.waitForLoadState('networkidle');assert.equal((await context.request.post(f.base+'/admin/metrics/verify',{headers:{Origin:'https://foreign.test'}})).status(),403);let started;for(let retry=0;retry<40;retry++){const next=page.waitForResponse(r=>r.url()===f.base+'/admin/metrics/verify'&&r.request().method()==='POST');console.log('click-start');await page.getByRole('button',{name:'Перепроверить страницы',exact:true}).click({noWaitAfter:true});console.log('click-end');started=await next;console.log('response-await-end');if(started.status()!==409)break;await page.waitForTimeout(500);}assert.equal(started.status(),202);console.log('status-start');await page.getByRole('status').filter({hasText:'Проверка запущена'}).waitFor();console.log('refresh-start');await page.getByRole('button',{name:'Обновить метрики',exact:true}).click({noWaitAfter:true});console.log('refresh-end');assert.deepEqual(await metrics(),expected);await page.screenshot({path:`${out}/started-${width}.png`,fullPage:true});report.screenshots.push(`started-${width}.png`);assert.deepEqual(errors,[]);
  report.checks.push({width,anonymous404:true,ordinary404:true,operator200:true,no_store:true,counts:expected,foreign403:true,accepted202:true,pending_fixture_count:1,refresh:true,layout:true,javascript_errors:0});await context.close();contexts.splice(contexts.indexOf(context),1);
 }
 report.status='pass';
}catch(e){report.status='failed';report.stage=stage;report.error=String(e.stack??e);process.exitCode=1;}
finally{report.finished_at=new Date().toISOString();fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));for(const c of contexts)await c.close();await browser.close();console.log(JSON.stringify(report));}
