from pathlib import Path
import hashlib,json,datetime,subprocess,os
r=Path('/tmp/n7-f11-pg-fixture-author-a22');inv=json.loads((r/'source-build-before.json').read_text());after=[]
for f in inv['files']:
 h=hashlib.sha256(Path(f['path']).read_bytes()).hexdigest();
 if not any(f['path'].endswith('/'+name) for name in ['tests/capacity-integration.test.ts','tests/f10-runtime-protocol.test.ts']):assert h==f['sha256'],f['path']
 after.append({**f,'sha256':h})
(r/'source-build-after.json').write_text(json.dumps({'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'files':after,'dist_count':len([f for f in after if '/dist/' in f['path']]),'unchanged':True},indent=2))
starts=[json.loads(p.read_text()) for p in r.glob('process-start-*.json')];guards=[json.loads(p.read_text()) for p in r.glob('guard-*.json')];assert len(starts)==len(guards),(len(starts),len(guards))
for g in guards:
 assert 'endedAt' in g
 try:current=Path(f"/proc/{g['pid']}/stat").read_text().split(' ')[21]
 except FileNotFoundError: current=None
 assert current!=g['startTicks'],g['pid']
(r/'native-process-receipts.json').write_text(json.dumps({'all_guarded_processes_exited':True,'starts':starts,'guard_exits':guards,'exec_sessions':{'82753':0,'69296':0,'40558':0}},indent=2))
revision=subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip();changes=subprocess.check_output(['git','diff-tree','--no-commit-id','--name-only','-r','HEAD'],text=True).splitlines();assert len(changes)==2
for name in ['types-final-exit.txt','lint-final-exit.txt','capacity-final-exit.txt','terminal-final-exit.txt','setup-final-exit.txt']:assert (r/name).read_text().strip()=='0',name
launch=json.loads((r/'pre-final-launch.json').read_text())
for f,h in launch['hashes'].items():assert hashlib.sha256(Path(f).read_bytes()).hexdigest()==h,f
sessions=[json.loads(p.read_text()) for p in r.glob('schema-session-*.json')];schemas=sorted(set(s['schema'] for s in sessions))
raw={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in r.iterdir() if p.is_file() and p.name!='seal.py'}
ended=datetime.datetime.now(datetime.timezone.utc);receipt={'work_unit_id':'f11-pg-fixture-author-a22','status':'completed','verdict':'candidate_for_fresh_HIGH_not_F11_accepted','ack_utc':'2026-10-07T03:20:55Z','ended_utc':ended.isoformat(),'elapsed_ms':int((ended-datetime.datetime(2026,10,7,3,20,55,tzinfo=datetime.timezone.utc)).total_seconds()*1000),'source_cutoff_utc':'2026-10-07T03:26:55Z','terminal_deadline_utc':'2026-10-07T03:28:55Z','baseline':'5c707737fdcb2be4c579eac4cbd71a9a026b8820','revision':revision,'profile':'model-routing-econom','requested_model':'gpt-6.1-sol','requested_effort':'medium','actual_model':None,'actual_effort':None,'usage':None,'cost':None,'measurement_gap':'Host actual model/effort/billing counters unavailable; no inferred measurements','allowed_files':changes,'checks':{'types':0,'targeted_lint':0,'full_genuine_F07_11tests':0,'terminal_public_preserved':0,'diff_check':0},'attempts':[{'id':'first','session':82753,'exit':0,'reason':'initial fixture corrected'},{'id':'retry','session':69296,'exit':0,'reason':'confirmed future verifier portability defect and missing retained digest evidence'},{'id':'final','session':40558,'exit':0,'reason':'coordinator required exact parent identity guard before migrate/reset'}],'production_and_build_inventory':'all A21 inventory except exactly two allowed tests byte unchanged; dist76 reused A21 native buildexit0, no new build','schemas_retained':schemas,'public_preservation':'full all-table count+sha256 before/after schema setup and terminal; final capacity raw contains before/after parent+public count/md5 equality','migration_proof':'stock001-011 then genuine migrate+ready twice through017; same credential envelope/state; capacity_lease zero; cross-schema FK zero','guard':'copied A21 numerical DNS/TCP admission; A22 exact parent or per-pool unique UUID upgrade schema verified and frozen per launch','children_joined':True,'raw_sha256':raw,'source_ownership_released':True,'database_ownership_released':True,'main_ledger_written':False,'gaps':['F11 fresh independent HIGH source review remains','Two full300 fleet witnesses remain, not run in A22','Full mandatory project suite remains verifier gate','Disk dipped below2GiB in parent observation and recovered; cause unknown; own each launch statvfs above2GiB','No actual model/effort/usage host counters']}
(r/'receipt.json').write_text(json.dumps(receipt,indent=2));(r/'receipt.md').write_text(f"A22 {revision}\nStatus: completed\nVerdict: candidate for fresh HIGH, not F11 acceptance\nFinished-At: {ended.isoformat()}\nExact two tests committed; full genuine F07 11 tests pass, types/lint0, public preserved, own schemas retained. Production/source/build inventory unchanged, dist76 reused. All native sessions joined0. Profile model-routing-econom; actual model/effort/usage unavailable. Evidence receipt.json includes full raw sha inventory and remaining gates.\n")
print(json.dumps({'revision':revision,'elapsed_ms':receipt['elapsed_ms'],'guarded_processes':len(guards),'schemas':schemas,'dist_count':len([f for f in after if '/dist/' in f['path']]),'receipt':str(r/'receipt.json')}))
