from pathlib import Path
p=Path('/tmp/n7-f10-restart-fix-20261006-a12/projects/07-cold-email-warmup/tests');f=p/'f10-runtime-protocol.test.ts';s=f.read_text().replace('let events:Record<string,any>[]=[],final:Record<string,any>[]=[];',"type Event={event_id:string;at:Date;kind:string;mailbox:string;body:{service_seq:number;scan_complete?:boolean;completed_at?:string;state?:string}};type Final={mailbox_id:string;scan_complete:boolean;pages:number;scan_state:string;reason:string;due_at:Date};let events:Event[]=[],final:Final[]=[];")
s=s.replace("assert.ok(final.find(e=>e.mailbox===c.boxes[4])!.scan_complete,'E really completed');","assert.notEqual(firstECompletion,null,'E really completed before worker drain');")
s=s.replace("  const eCompletions=", "  const eFirst=selected.find(e=>e.mailbox===c.boxes[4])!;for(const id of c.boxes.slice(0,4)){const native=c.traffic as {mailbox:string;started:number;completed?:number;beforeIO?:{state:string;service_seq:string}}[];assert.ok(native.some(e=>e.mailbox===id&&e.started>=begun&&e.completed!==undefined&&e.completed<=eFirst.at.getTime()&&e.completed-e.started>=5000),'each A-D first scheduled native page succeeds for at least five seconds before E selection');}for(const row of c.eligibility.rows){assert.ok(row.next_check_at.getTime()<=selected[0]!.at.getTime(),'all five eligible before first claims');}const eDue=c.eligibility.rows.find(r=>r.mailbox_id===c.boxes[4])!.due_at.getTime();assert.ok(c.eligibility.rows.filter(r=>r.mailbox_id!==c.boxes[4]).every(r=>r.due_at.getTime()<eDue),'E is later due than existing A-D rescans');\n  const eCompletions=")
s=s.replace("joins,eligibility:","joins,firstECompletion,eligibility:")
s=s.replace("ownership:events.filter(e=>['selection','yield'].includes(e.kind)&&e.mailbox===id)","ownership:events.filter(e=>['selection','yield'].includes(e.kind)&&e.mailbox===id),ownershipDurationsMs:events.filter(e=>e.kind==='selection'&&e.mailbox===id).map(e=>({selected:e.at.getTime(),released:events.find(v=>v.kind==='yield'&&v.mailbox===id&&Number(v.event_id)>Number(e.event_id))?.at.getTime()??null}))")
f.write_text(s)
S=Path('/tmp/n7-f10-adversarial-fairness-a24/compact-shadow/tests')
for n in ['f10-runtime-protocol.test.ts','f10-runtime-fixture.ts','f10-runtime-process-fixture.ts']:(S/n).write_bytes((p/n).read_bytes())
