from pathlib import Path
import json,hashlib,datetime,subprocess,fcntl
R=Path('/tmp/n7-f10-adversarial-fairness-a24');P=Path('/tmp/n7-f10-restart-fix-20261006-a12/projects/07-cold-email-warmup');S=R/'compact-shadow';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat();allowed=['tests/f10-runtime-protocol.test.ts','tests/f10-runtime-process-fixture.ts','tests/f10-runtime-fixture.ts'];old=json.loads(Path('/tmp/n7-f10-pair-fixture-fix-a22/final-manifest.json').read_text());m=json.loads(json.dumps(old));drift=[]
for group in ['source','build','db']:
 for f,h in old[group].items():
  if f not in allowed and sha(P/f)!=h:drift.append((group,f))
assert not drift,drift
for f in allowed:m['source'][f]=sha(P/f);assert sha(S/f)==sha(P/f),f
revision=subprocess.check_output(['git','rev-parse','HEAD'],cwd=P,text=True).strip();m['revision']=revision;m['baseline']='74766159b38c0e346832992c3be7b62851aad577';(R/'final-manifest.json').write_text(json.dumps(m,indent=2)+'\n')
terminal=json.loads((R/'common-exact-restored-v3-terminal.json').read_text());assert terminal['PG']['quiescent'] and not terminal['remaining_owned_nodes'];assert terminal['inputs_unchanged'] and terminal['runner_sha256_unchanged'];lock=open('/tmp/codex-heavy-build.lock','rb');fcntl.flock(lock,fcntl.LOCK_EX|fcntl.LOCK_NB);fcntl.flock(lock,fcntl.LOCK_UN);lock.close()
negatives=[]
for name in ['oldest-due','reset-yield-sequence']:
 n=json.loads((R/(name+'-negative-v3-terminal.json')).read_text());t=(R/(name+'-negative-v3.tap')).read_text();restore=json.loads((R/(name+'-exact-restore-v3.json')).read_text());assert n['native_returncode']==1 and not n['timed_out'] and 'ERR_ASSERTION' in t and 'fair E selection precedes ANY A-D second quantum after actual restart' in t and restore['exact_equal'];negatives.append({'name':name,'native_returncode':1,'named_assertion':'fair E selection precedes ANY A-D second quantum after actual restart','terminal_sha256':sha(R/(name+'-negative-v3-terminal.json')),'exact_restore':restore})
assert sha(S/'dist/runtime/store.js')==old['build']['dist/runtime/store.js'];guards=[json.loads(p.read_text()) for p in R.glob('guard-*.json')]
receipt={'at':now(),'status':'PARTIAL','overall_F10_acceptance':False,'revision':revision,'source_freeze':now(),'source120_build73_SQL15_drift_except_three_authorized_tests':drift,'allowed_delta':{f:{'before':old['source'][f],'after':sha(P/f)} for f in allowed},'typecheck':{'native_exit':0,'command':'node_modules/.bin/tsc --noEmit'},'lint':{'native_exit':0,'command':'node_modules/.bin/eslint tests/f10-runtime-protocol.test.ts tests/f10-runtime-fixture.ts tests/f10-runtime-process-fixture.ts'},'build_reuse':{'count':73,'manifest':'/tmp/n7-f10-pair-fixture-fix-a22/final-manifest.json','unchanged':True},'existing_green_reuse':{'healthy330':'/tmp/n7-f10-frozen-verify-a20/terminal-seal.json','wholePG169':'/tmp/n7-f10-frozen-verify-a20/fullpg-terminal.json','physical':'/tmp/n7-f10-independent-review-a23/review.md supporting A16'},'negative_checks':negatives,'native_current_source_GREEN':{'status':'incomplete','cause':'owned common stage gracefully terminated for mandatory A24 freeze; not a runtime defect and not a passing test','native_returncode':terminal['native_returncode'],'terminal':terminal},'auto_review_rejection':{'action':'42s window and replacing exact twenty-page assertion with7–20 range','reason':'would weaken mandatory exact20-page assertion; rejected action did not execute','safe_resolution':'exact20-page assertion and timing/cap retained; monotonic wait >=5000ms corrected fixture'},'guards':{'receipts':len(guards),'socketDenied':sum(g['socketDenied'] for g in guards),'dnsDenied':sum(g['dnsDenied'] for g in guards),'note':'guard blocks all denied attempts; denial receipts preserved, no external reachability inferred'},'ownership_release':{'source':'released to coordinator','ownDB':'n7f10_a2 released to coordinator','PG':terminal['PG'],'owned_nodes':terminal['remaining_owned_nodes'],'mutex':'released and independently reacquired'},'remaining_AC':['current-source native20page common exact-restored GREEN then fresh independent HIGH final reconciliation'],'next_executor':'/root/n7_sol_coordinator; assign fresh HIGH readonly operational verification and independent reconciliation','profile':'model-routing-econom','requested_model':'gpt-6.1-sol','requested_effort':'medium','actual_model':None,'actual_effort':None,'usage':None,'cost':None,'measurement_gap':'host metadata unavailable','duration_seconds':(datetime.datetime.now(datetime.timezone.utc)-datetime.datetime.fromisoformat('2026-10-06T20:49:05.366124+00:00')).total_seconds(),'raw_sha256':{p.name:sha(p) for p in R.iterdir() if p.is_file() and p.name!='terminal-seal-partial.json'}}
(R/'terminal-seal-partial.json').write_text(json.dumps(receipt,indent=2)+'\n')
(R/'receipt.md').write_text(f'''# A24 corrective test receipt — PARTIAL\n\nRevision `{revision}`. Only the three authorized test files changed; source120 except these tests, build73 and SQL15 remain matched to A22. Typecheck and focused lint native exit0.\n\nBoth corrected oldest-due and reset-yield-sequence shadow mutations produced native exit1 on the named assertion “fair E selection precedes ANY A-D second quantum after actual restart”; exact original bytes were restored after each. There is no current-source passing baseline, no chronological0/1/0 claim, and no overall F10 acceptance.\n\nThe common restored native process was gracefully terminated after launch21:04:28.982897 because measured110–118s duration could not join before21:06:05 freeze. Its exit1 is incomplete budget termination, not a product failure. All owned nodes joined, PG quiescent, heavy mutex released and independently reacquired.\n\nRemaining: fresh native current-source GREEN of the exact20page witness, then independent HIGH reconciliation. Source/ownDB released to coordinator, who owns the next executor. Launch command/preloads/fixture hashes and each native exit are in unique ready/launched/terminal files; final source/build/SQL hashes in final-manifest.json. All5 participant event denominators remain in every completed fairness raw receipt, including partial/held A–D and E's genuine completions.\n\nThe42s/7–20 proposal was rejected by automatic approval review as weakening the exact20page assertion; it did not execute. The retained fix waits a measured monotonic5000ms before responding and keeps the exact20page assertion.\n\nProfile model-routing-econom; requested gpt-6.1-sol/medium; actual model/effort/token/cost unavailable, recorded null. Duration{receipt['duration_seconds']:.1f}s.\n''')
(R/'verification-handoff.json').write_text(json.dumps({'revision':revision,'candidate':str(P),'source_manifest':str(R/'final-manifest.json'),'source_manifest_sha256':sha(R/'final-manifest.json'),'launch_packet':str(R/'launch.json'),'launch_sha256':sha(R/'launch.json'),'finding_packet':'/tmp/n7-f10-independent-review-a23/review.md','finding_sha256':'833109353de9e01b1238dcb9d328982cae9cdd18ce8d0982ed5fda5a65a1ba05','normative_revision':'dfb3219e58a86dbf0a16b68e4fb6f26def99a4da','command':['/tmp/n7-expanded-runtime-20261006/bin/node','node_modules/tsx/dist/cli.mjs','--test','--test-concurrency=1','--test-name-pattern=native five-second rescans','tests/f10-runtime-protocol.test.ts'],'guard':str(R/'guard.mjs'),'guard_sha256':sha(R/'guard.mjs'),'runner':str(R/'run.py'),'runner_sha256':sha(R/'run.py'),'environment_source':'/tmp/n7-f09-verify-a2/env.sh','DATABASE_NAME':'n7f10_a2','F10_EVIDENCE_DIR':'new unique coordinator-owned evidence root','requirements':'new fixture/runner hashes before launch; own heavy mutex; ownDB asserted pre-reset and quiescent; fresh unique raw TAP/exits; current20page nativeGREEN only, reuse unchanged330/wholePG/physical','new_record_instruction':'read legitimate launch/review/normative and objective raw; do not inherit author reasoning; this operational handoff records authority/command only'},indent=2)+'\n')
print(json.dumps({'revision':revision,'status':'PARTIAL','negative_checks':2,'typecheck':0,'lint':0,'remaining':'native current-source GREEN + independent HIGH','ownership':'released','duration_seconds':receipt['duration_seconds']}))
